name: .NET Core

on:
  push:
    branches:
      - feature/duplicate-db-onebyone
jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Publish application
      run: dotnet publish --configuration Release --output ./artifacts ./src/Microsoft.Health.Fhir.R4.Web/Microsoft.Health.Fhir.R4.Web.csproj
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ci-artifact
        path: ./artifacts
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'perftest0522'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_76253104e63c421e84307a1d773bf516 }}
        package: ./artifacts
